preload = ~/Wallpapers/colorfulfox.png
preload = ~/Wallpapers/colorfulfox_resized.png
preload = ~/Wallpapers/neon_swordsman.png 
wallpaper = ,~/Wallpapers/colorfulfox_resized.png 
splash = true
ipc = off

