preload = ~/Wallpapers/colorfulfox.png
preload = ~/Wallpapers/colorfulfox_resized.png
preload = ~/Wallpapers/neon_swordsman.png 
preload = ~/Wallpapers/purple_tiger.png 
wallpaper = ,~/Wallpapers/purple_tiger.png 
splash = true
ipc = off

