#==============================================================================================================
 
# colors for hyprland
source = ~/.cache/wal/hypr-color.conf

#==============================================================================================================

# the important variablesva
source = ~/.config/hypr/variables.conf

#==============================================================================================================

# env varibles
source = ~/.config/hypr/env_var.conf


#==============================================================================================================

# monitors ( for now i only have one ) cz im poor
source = ~/.config/hypr/monitors.conf

#==============================================================================================================

# startup apps 
source = ~/.config/hypr/startupapps.conf

#==============================================================================================================

# file for keybinding
source = ~/.config/hypr/keybindings.conf

#==============================================================================================================




input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 5
    touchpad {
        natural_scroll = true
        disable_while_typing = true
        scroll_factor = 1.1
        tap-to-click = true
        tap-and-drag = true
    }
    sensitivity = 0.5 
}



#==============================================================================================================

general {
    gaps_in = 2
    gaps_out = 2
    border_size = 2
    col.active_border = rgb($color4)
    col.inactive_border = rgb(000000)
    cursor_inactive_timeout = 0
    layout = master
    allow_tearing = false
    resize_on_border = true
    hover_icon_on_border = true
}


#==============================================================================================================

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
}


#==============================================================================================================

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.1
    animation = windows, 1, 2, myBezier
    animation = windowsOut, 1, 2, default, popin 80%
    animation = border, 1, 2, default
    animation = borderangle, 1, 2, default
    animation = fade, 1, 2, default
    animation = workspaces, 1, 2, default
}

#==============================================================================================================

dwindle {
    preserve_split = true
    smart_split = true
}


master {
    new_is_master = true
    no_gaps_when_only = true
}


gestures {
    workspace_swipe = off
}


#==============================================================================================================

misc {
    layers_hog_keyboard_focus = true
    disable_hyprland_logo = true
}

#==============================================================================================================

device:epic-mouse-v1 {
    sensitivity = -0.5
}

#==============================================================================================================

windowrule = workspace 1, ^(.*kitty.*)$
windowrule = workspace 2, ^(.*firefox.*)$
windowrule = workspace 2, ^(.*qutebrowser.*)$
