preload = ~/Wallpapers/colorfulfox.png
preload = ~/Wallpapers/colorfulfox_resized.png
preload = ~/Wallpapers/neon_swordsman.png 
preload = ~/Wallpapers/purple_tiger.png 
preload = ~/Wallpapers/wallhaven-yx3x3l.png 
preload = ~/Wallpapers/bw_goku.png 
preload = ~/Wallpapers/arch_btw.png 
wallpaper = ,~/Wallpapers/arch_btw.png 
splash = true
ipc = off

