# the variables
$mainMod = SUPER
$menus = rofi -show run -p "everything: "
$alt = Alt
$terminal = kitty
$logout = loginctl ,terminate-user $USER
$shutdown = systemctl poweroff
$suspend = systemctl suspend

