# the variables
$mainMod = SUPER
$menus = bemenu-run
$alt = Alt
$terminal = kitty
$logout = loginctl terminate-user $USER
$shutdown = systemctl poweroff
$suspend = systemctl suspend
$reboot = systemctl reboot
