set-option -sa terminal-overrides ",xterm*:Tc"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -s default-terminal 'tmux-256color'
set -g prefix C-p
unbind C-b

#splitting
bind | split-window -h
bind - split-window -v

# Pane navigation with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-l next-window

# Resize panes
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

set -g mouse on
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind R command-prompt -p "Rename window:" "setw window-renam"
bind < command-prompt -p "Switch to window:" "select-window -t :"
setw -g mode-keys vi

# carbonfox colorscheme for tmux

# this is the pywal colorscheme for tmux
set -g @plugin 'TechnicalDC/tmux-pywal-theme'


bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-paste"

run '~/.tmux/plugins/tpm/tpm'
