source ~/.cache/wal/colors.sh
setopt autocd beep extendedglob nomatch notify
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.histfile
zstyle :compinstall filename '/home/shashank/.zshrc'

autoload -Uz compinit
zstyle ':completion"*' menu select
zmodload zsh/complist
compinit
 
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source /usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# Path additions (using PATH instead of fish_user_paths)
# ranking mirror
# first go to su -
# cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
# then do the 
# rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
# all of this should be done while youre in su -
# if anything gets fucked up just try this
# sudo reflector --country 'India' --latest 5 --age 2 --fastest 5 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
# this is using reflector
# i saw once for converting the doc files and stuff you can use soffice
# its from libreoffice 
# you can do soffice --headless --convert-to pdf *.docx
 
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.cargo/env:$PATH"
export PATH="$HOME/binaries:$PATH"
export PATH="$HOME/.config/scripts:$PATH"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="/home/shashank/.nimble/bin:$PATH"
export PATH="$HOME/.local/share/:$PATH"
export PATH="$PATH/home/shashank/.local/bin:$PATH"
export PATH="$HOME/.zfunc/:$PATH"
export XDG_CURRENT_DESKTOP="Hyprland"
fpath+=~/.zfunc

# Environment variables
export EDITOR="nvim"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# Aliases (using the same syntax)
alias l='lsd -al'
alias ls='lsd'
alias f='cd $(fd -t d -H | fzf)'
alias rankmirr='rankmirrors -n 6 /etc/pacman.d/mirrorlist.bak > /etc/pacman.d/mirrorlist'
alias gall='git add . && git commit -am "$(date)" && git push -u origin main'
alias t='a=$(fd -t d -H | fzf) && tmux new -c "$a" -s "$(basename "$a")"'
alias ff='fastfetch'
alias cdir='pwd | wl-copy'
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to full|percentage"'
alias cd='z'
alias file='yazi'
alias convertpng='mogrify -format png *.jpg'
alias nvim='neovide'

# Starship initialization
eval "$(starship init zsh)"

# opam configuration (using source as in Zsh)
source /home/shashank/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# for zoxide
eval "$(zoxide init zsh)"
